include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/publish.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

build:
  before_script:
    - echo "before install poetry"
    - !reference [default, before_script]

test:
  script:
    - echo "example override"
    - !reference [.test, script]

publish:
  script:
    - echo "publish as $CI_COMMIT_TAG"

pages:
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    PAGES_BRANCH_NAME: pages
  before_script: []
  script:
    - apt update && apt -qqy install git
    - mkdir public
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - vp=public/versions.json
    - if [[ $(git branch --list $PAGES_BRANCH_NAME) ]]; then
        git checkout $PAGES_BRANCH_NAME;
        python -c "import json; lst = json.load(open('${vp}')); json.dump([dict(version='${CI_COMMIT_TAG}'), *lst], open('${vp}', 'w'), indent=4)"
      else
        git checkout --orphan $PAGES_BRANCH_NAME;
        git rm -rf .;
        echo "[]" > $vp;
      fi
    - git add public
    - git commit -m "Deploy $CI_COMMIT_SHA"
    - git remote set-url origin "https://${GITLAB_USER_NAME}:${CI_PUSH_TOKEN}@gitlab.com/$CI_PROJECT_PATH.git"
    - git push --set-upstream origin $PAGES_BRANCH_NAME -o ci.skip
  artifacts:
    paths:
    - public
