include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/publish.gitlab-ci.yml
  - local: ci-templates/docs.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

default:
  before_script:
    - export
    - echo "before_script"
  after_script:
    - echo "after_script"

build:
  script:
    - echo "before build"
    - !reference [.build, script]

test:
  script:
    - echo "before install poetry"
    - !reference [.snippets, install-poetry]
    - echo "after install poetry"
    - poetry run pytest --version
    - poetry run pytest -vv

publish:
  rules:
    - if: $CI_MERGE_REQUEST_IID
      variables:
        CI_COMMIT_TAG: 0+test.${CI_COMMIT_SHORT_SHA}
    - !reference [.publish, rules]

update-pages:
  rules:
    - if: $CI_MERGE_REQUEST_IID
      variables:
        CI_COMMIT_TAG: 0+test
        CI_COMMIT_REF_NAME: 0+test
    - !reference [.update-pages, rules]
