include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/publish.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

test:
  script:
    - echo "example override"
    - !reference [.test, script]

publish:
  rules:
    - when: never
