include:
  - local: ci-templates/test.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

build:
  extends: .build_template

test:
  extends: .test_template

lint:
  extends: .lint_template
