include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/publish.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

build:
  before_script:
    - echo "before install poetry"
    - !reference [default, before_script]

test:
  script:
    - echo "example override"
    - !reference [.test, script]

publish:
  script:
    - echo "publish as $CI_COMMIT_TAG"

pages:
  stage: deploy
  variables:
    PAGES_BRANCH_NAME: pages
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mkdir public
    - echo "docs of $CI_COMMIT_TAG" > public/$CI_COMMIT_TAG
    - if [[ `git branch --list $PAGES_BRANCH_NAME` ]]; then
        git checkout $PAGES_BRANCH_NAME
      else
        git checkout --orphan $PAGES_BRANCH_NAME;
        git rm -rf .;
    - git add public
    - git commit -m "Deploy $CI_COMMIT_TAG"
  artifacts:
    paths:
    - public
