include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/publish.gitlab-ci.yml
  - local: ci-templates/docs.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

build:
  before_script:
    - echo "before install poetry"
    - !reference [.install_poetry]

test:
  script:
    - echo "example override"
    - !reference [.test, script]

publish:
  script:
    - echo "publish as $CI_COMMIT_TAG"
