include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/deploy.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

build:
  extends: .build_template

test:
  extends: .test_template

lint:
  extends: .lint_template
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

publish:
  extends: .publish_template
