include:
  - local: ci-templates/test.gitlab-ci.yml
  - local: ci-templates/deploy.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

publish:
  extends: .publish_template
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  script:
    - echo "example override"
    - !reference [.test_template, script]
