[nitpick.files.absent]
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"
".isort.cfg" = "Move values to setup.cfg, section [isort]"

["setup.cfg"."coverage:report"]
# Regexes for lines to exclude from consideration
exclude_lines = """
    # Don't complain about missing debug-only code:
    def __repr__

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if tests don't hit abstract class
    abc.
    ABC
    @abstractmethod

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:

    # Manually escape
    pragma: no cover
"""
ignore_errors = true
omit = "*__init__.py, *tests/*"

["setup.cfg"."coverage:run"]
branch = true

["setup.cfg".flake8]
max-line-length = 119
# E125: continuation line under-indented for hanging indent
# E266: too many leading '#' for block comment
# E731: assign lambda
# W503: line break before binary operator
ignore = "E125,E266,E731,W503"
exclude = ".git,__pycache__,.venv,venv,env,build,docs,*/__init__.py"
max_complexity = 20
statistics = true
inline-quotes = "single"

["setup.cfg".isort]
# Reference
# https://pycqa.github.io/isort/docs/configuration/options/
line_length = 119
multi_line_output = 5
include_trailing_comma = true
balanced_wrapping = true
lines_after_imports = 2

["setup.cfg"."tool:pytest"]
addopts = "--pdbcls IPython.terminal.debugger:TerminalPdb"

["pyproject.toml".tool.poetry.dev-dependencies]
ipython = "*"
ipdb = "*"
jedi = "<0.18.0"
pytest = "*"
pytest-cov = "*"
