["setup.cfg".flake8]
max-line-length = 119
# E125: continuation line under-indented for hanging indent
# E266: too many leading '#' for block comment
# E731: assign lambda
# W503: line break before binary operator
ignore = "E125,E266,E731,W503"
exclude = ".git,__pycache__,.venv,venv,env,build,docs,*/__init__.py"
max_complexity = 20
statistics = true
inline-quotes = "single"

["setup.cfg".isort]
# Reference
# https://pycqa.github.io/isort/docs/configuration/options/
line_length = 119
multi_line_output = 5
include_trailing_comma = true
balanced_wrapping = true
lines_after_imports = 2

["pyproject.toml".tool.poetry.dev-dependencies]
ipython = "*"
ipdb = "*"

["pyproject.toml".tool.pytest.ini_options]
addopts = "--pdbcls IPython.terminal.debugger:TerminalPdb"
