.upload_pypi_template:
  stage: deploy
  variables:
    POETRY_VERSION: "==1.1.*"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python -V
    - pip install "poetry${POETRY_VERSION}"
    - echo $CI_COMMIT_TAG
    - poetry version $CI_COMMIT_TAG
    - poetry config repositories.project_pypi $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
    - poetry publish --build -r project_pypi -u gitlab-ci-token -p $CI_JOB_TOKEN

.test_upload_pypi_template:
  stage: deploy
  variables:
    POETRY_VERSION: "==1.1.*"
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - python -V
    - pip install "poetry${POETRY_VERSION}"
    - poetry config repositories.project_pypi $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
    - poetry publish --dry-run --build -r project_pypi -u gitlab-ci-token -p $CI_JOB_TOKEN

upload_pypi:
  extends: .upload_pypi_template

test_upload_pypi:
  extends: .test_upload_pypi_template
