[nitpick.files.absent]
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"
".isort.cfg" = "Move values to setup.cfg, section [isort]"

["setup.cfg".flake8]
max-line-length = 119
ignore = """ 
    # Do not assign a lambda expression, use a def (https://www.flake8rules.com/rules/E731.html)
    E731,
    # Line break occurred before a binary operator (https://www.flake8rules.com/rules/W503.html)
    W503,
    # Too strict & subjective
    NIP,WPS
    # Docstring related, not ready...
    D,DAR,RST
    # Found commented out code, not ready...
    E800
"""
exclude = """ 
    .git,
    __pycache__,
    # virtual environment
    .venv/,
    venv/,
    env/
    build/
    # sphinx docs
    docs/
"""
per-file-ignores = """ 
    # allow non-optimized or insecure code in tests
    *test*.py: S
"""
max_complexity = 20
statistics = true
inline-quotes = "single"

["setup.cfg".isort]
# Reference
# https://pycqa.github.io/isort/docs/configuration/options/
line_length = 100
multi_line_output = 5
include_trailing_comma = true
balanced_wrapping = true
lines_after_imports = 2

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = ">=0.17"
