include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml

.build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - poetry install
  cache:
    paths:
      - $POETRY_VIRTUALENVS_PATH
    key:
      files:
        - poetry.lock
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $POETRY_CACHE_DIR
      - $POETRY_HOME
      - $POETRY_VIRTUALENVS_PATH
    expire_in: 60 mins

build:
  extends: .build
