include:
  - local: ci-templates/snippets.gitlab-ci.yml

.build:
  script:
    - !reference [.snippets, install-poetry]
    - poetry install -vv
  cache:
    paths:
      - $POETRY_VIRTUALENVS_PATH
    key:
      files:
        - poetry.lock
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $POETRY_CACHE_DIR
      - $POETRY_HOME
      - $POETRY_VIRTUALENVS_PATH
    expire_in: 1 day

build:
  stage: build
  extends: .build
