include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml

.build:
  stage: build
  script:
    - poetry install
  cache:
    paths:
      - $POETRY_VIRTUALENVS_PATH
    key:
      files:
        - poetry.lock
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $POETRY_CACHE_DIR
      - $POETRY_HOME
      - $POETRY_VIRTUALENVS_PATH
    expire_in: 1 day

build:
  extends: .build
