include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml

# HACK
.install_build_requires: &install_build_requires
  - poetry run pip install toml
  - build_requires=`poetry run python -c "import toml; print(*toml.load('pyproject.toml')['build-system']['requires'])"`
  - echo $build_requires
  - poetry run pip install $build_requires

.publish_template:
  stage: deploy
  rules:
    # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - if: $CI_COMMIT_TAG =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
  script:
    - *install_build_requires
    - poetry config repositories.project_pypi $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
    - echo "publish as $CI_COMMIT_TAG"
    - poetry version $CI_COMMIT_TAG
    - poetry publish --build -r project_pypi -u gitlab-ci-token -p $CI_JOB_TOKEN
