include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml

.test-docs:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - poetry run sphinx-build docs/source docs/build/html

.pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - poetry run sphinx-build docs/source public
  artifacts:
    paths:
    - public

test-docs:
  extends: .test-docs

pages:
  extends: .pages
