variables:
  PIP_CACHE_DIR: .cache/pip
  POETRY_CACHE_DIR: .cache/pypoetry
  POETRY_VIRTUALENVS_PATH: venv
  POETRY_HOME: .poetry

.install_poetry: &install_poetry
  - if ! command -v poetry &> /dev/null;
    then
      echo "poetry not found, start installing...";
      apt update && apt install -y curl;
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -;
      source $POETRY_HOME/env;
    else
      echo "poetry exists, skip installing";
    fi
  - poetry -V

default:
  image: python:3.7
  before_script:
    - *install_poetry
