variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  POETRY_CACHE_DIR: $CI_PROJECT_DIR/.cache/pypoetry
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/venv
  POETRY_HOME: $CI_PROJECT_DIR/.poetry

.install_poetry: &install_poetry
  - >
    if ! test -d $POETRY_HOME; then
      echo "poetry not found, start installing..."
      curl -sSL https://install.python-poetry.org | python3.7 - -y
    else
      echo "find poetry at $POETRY_HOME, skip installing"
    fi
  - export PATH="$POETRY_HOME/bin:$PATH" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - poetry -V

default:
  image: quay.io/pypa/manylinux2014_x86_64:latest
  before_script:
    - *install_poetry
