include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml

variables:
  POETRY_REPOSITORIES_PROJECT_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  POETRY_HTTP_BASIC_PROJECT_USERNAME: gitlab-ci-token
  POETRY_HTTP_BASIC_DYSK_LABS_PASSWORD: ${CI_JOB_TOKEN}

# HACK
.install_build_requires: &install_build_requires
  - poetry run pip install toml
  - build_requires=`poetry run python -c "import toml; print(*toml.load('pyproject.toml')['build-system']['requires'])"`
  - echo $build_requires
  - poetry run pip install $build_requires

.test-publish:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - *install_build_requires
    - echo "no tag, dry run"
    - poetry publish --build -r project --dry-run

.publish:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - *install_build_requires
    - echo "publish as $CI_COMMIT_TAG"
    - poetry version $CI_COMMIT_TAG
    - poetry publish --build -r project

test-publish:
  extends: .test-publish

publish:
  extends: .publish
