include:
  - local: ci-templates/snippets.gitlab-ci.yml

variables:
  # might be false positive but easy, just let the pipeline fail if invalid
  PUBLISH_TAG_PATTERN: '/^v?\d+\.\d+\.\d+/'

.test-publish:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - !reference [.snippets, install-poetry]
    - !reference [.snippets, install-build-requires]
    - poetry config repositories.project_pypi $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
    - poetry publish --build -r project_pypi -u gitlab-ci-token -p $CI_JOB_TOKEN --dry-run
  artifacts:
    paths:
      - dist
    expire_in: 1 day

.publish:
  rules:
    - if: $CI_COMMIT_TAG =~ $PUBLISH_TAG_PATTERN
  script:
    - !reference [.snippets, install-poetry]
    - !reference [.snippets, install-build-requires]
    - echo "publish as $CI_COMMIT_TAG"
    - poetry config repositories.project_pypi $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
    - poetry version $CI_COMMIT_TAG
    - poetry publish --build -r project_pypi -u gitlab-ci-token -p $CI_JOB_TOKEN

test-publish:
  stage: test
  extends: .test-publish

publish:
  stage: deploy
  extends: .publish
