include:
  - local: ci-templates/install-poetry-before-script.gitlab-ci.yml
  # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

.build_template:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - poetry install
  cache:
    paths:
      - $POETRY_VIRTUALENVS_PATH
    key:
      files:
        - poetry.lock
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $POETRY_CACHE_DIR
      - $POETRY_HOME
      - $POETRY_VIRTUALENVS_PATH
    expire_in: 60 mins

.test_template:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - poetry run pytest --version
    - poetry run pytest -vv
  coverage: '/^TOTAL.+?(\d+\%)$/'

.lint_template:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - "**/*.py"
  # lint in venv in case there's any lint extension
  script:
    - poetry run flake8 --version
    - poetry run flake8 --extend-exclude .poetry

build:
  extends: .build_template

test:
  extends: .test_template

lint:
  extends: .lint_template
